name: Auto Merge PRs for Specific File

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: List files changed in the PR
        id: file_changes
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}:refs/remotes/origin/pr/${{ github.event.pull_request.number }}
          git diff --name-only origin/pr/${{ github.event.pull_request.number }} > files_changed.txt
          cat files_changed.txt

      - name: Check if specific file is modified
        id: check_file
        run: |
          if grep -q "assets/js/contributors.js" files_changed.txt; then
            echo "File found"
            echo "::set-output name=file_modified::true"
          else
            echo "File not found"
            echo "::set-output name=file_modified::false"
          fi

      - name: Merge the PR if the specific file is modified
        if: steps.check_file.outputs.file_modified == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
