name: Auto Merge PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Fetch all history and branches
          fetch-depth: 0

      - name: Check for Changes
        id: check_changes
        run: |
          # Get the default branch (main or master)
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

          # Get the list of changed files
          changed_files=$(git diff --name-only origin/$DEFAULT_BRANCH ${{ github.sha }})

          # Count the number of modified files
          file_count=$(echo "$changed_files" | wc -l)

          # Check if the only modified file is contributors.js
          if [[ $file_count -eq 1 && "$changed_files" == "./assets/js/contributors.js" ]]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Merge the PR if the file has been changed
        if: env.changes_detected == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
